### ISSUE TITLE
Simplify the process of creating realizations from configuration

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/ngen#121]
The current process for creating a set of realizations from the configuration involves reading the JSON, loading specifications into `Realization_Config` objects, then later calling `get_realization()` from the config object, which then calls a separate `get_X` function for the proper realization type, which then reads a static array of required fields, then constructs the parameters and calls the constructor for the appropriate realization.

Instead, the JSON reading should yield the JSON objects that can then be used to create the realizations and bypass `Realization_Config` altogether.

The arrays of parameter names can then be moved to the realizations themselves and each realization can have a constructor that takes the JSONProperties as a parameter.

**Comment by ZacharyWills** [comment]
Does this issue refer to this Realization_Config? https://github.com/NOAA-OWP/ngen/blob/ec52ae4664b70e55e676a0168cfccfaf3cf22f42/src/realizations/catchment/Realization_Config_Reader.cpp

If so I would like to better comment that code for refactoring, so that there's nothing lost when transforming the JSON request into the JSON objects.

**Comment by christophertubbs** [comment]
Yeah, it touches on Realization_Config and Realization_Config_Reader. The first shake at a solution is at:

**Comment by hellkite500** [comment]
@christophertubbs has this moved with any of the changes in formulation manager?
