### ISSUE TITLE
basin_id?

### ISSUE THREAD

**Issue by dblodgett-usgs** [NOAA-OWP/ngen#143]
I don't want to butt into #142 so I'll ask over here.

What's a basin? I didn't think we were working with that concept.

**Comment by hellkite500** [comment]
@dblodgett-usgs @jdmattern-noaa I believe this is just some syntactic carryover from the early development of the forcing module prototype.  Turns out the id variable isn't event currently in use, but may have significance later on.  I do recommend renaming this to `catchment_id` or whatever variable name we are using in other parts of the code to maintain consistent identification.

**Comment by dblodgett-usgs** [comment]
OK - Got it.
