### ISSUE TITLE
Run Failure (alt-modular)

### ISSUE THREAD

**Issue by ZacharyWills** [NOAA-OWP/ngen#263]
Test and Validation GitHub Action fails with regards to cloning a model for inclusion with nGen 

## Current behavior

```
Please make sure you have the correct access rights
14
and the repository exists.
15
fatal: clone of 'git@github.com:NOAA-OWP/alt-modular.git' into submodule path '/home/runner/work/ngen/ngen/extern/alt-modular/alt-modular' failed
16
Failed to clone 'extern/alt-modular/alt-modular'. Retry scheduled
17
Cloning into '/home/runner/work/ngen/ngen/extern/pybind11'...
18
Cloning into '/home/runner/work/ngen/ngen/extern/t-route'...
19
Cloning into '/home/runner/work/ngen/ngen/test/googletest'...
20
Cloning into '/home/runner/work/ngen/ngen/extern/alt-modular/alt-modular'...
21
git@github.com: Permission denied (publickey).
22
fatal: Could not read from remote repository.
23

24
Please make sure you have the correct access rights
25
and the repository exists.
26
fatal: clone of 'git@github.com:NOAA-OWP/alt-modular.git' into submodule path '/home/runner/work/ngen/ngen/extern/alt-modular/alt-modular' failed
27
Failed to clone 'extern/alt-modular/alt-modular' a second time, aborting
28
```

## Expected behavior
Models should build, test and validate

## Steps to replicate behavior (include URLs)

1. Run action

**Comment by jdmattern-noaa** [comment]
I guess a decision needs to be made about whether or not to make alt-modular public. Otherwise, we can't include it in the tests.

**Comment by robertbartel** [comment]
@jdmattern-noaa, @ZacharyWills, the work to get the relevant components currently in _alt-modular_ into public repos is already ongoing.  Not sure when it will all be completed.

However, the appropriate fix for this is, indeed, to not include those in our tests, or at least not in the tests of external BMI module integration functionality.  

Instead, we need to write custom "dummy" BMI module(s) just for testing purposes, maintained within this project, that basically use an identity function (or something close to that) instead of an actual physics model.  I.e., these tests should only fail if the framework components break, not if an upstream model under development breaks (or worse, just changes slightly).

That said, an additional suite of tests for testing external coupled models is probably also a good idea.  It just should be separated from the automated testing that gets run here any time we do a change or PR.

**Comment by ZacharyWills** [comment]
@robertbartel What do you think of testing the framework model coupling in this repo (the ability to take externally coupled models at all) and then leaving each to their own implementation in their own repos?

**Comment by robertbartel** [comment]
@ZacharyWills, NGen+external_model integration test _execution_ does not need to be part of the automation in the NGen repo's Github Actions.  It only ever was because we needed something to test the coupling functionality against.  PR #270 will take care of that.

As for where NGen+external_model integration test _code_ needs to be, I can see arguments for including it either here or in the external model's repo (or both).  But that discussion can be tabled and had independently, since we can always create additional testing targets that don't get called by the Actions.

**Comment by ZacharyWills** [comment]
Sounds good, Closing.
