### ISSUE TITLE
Fix design of _ForcingProvider_ regarding getting begin and end times

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/ngen#337]
The _ForcingProvider_ interface needs to be extended to provided a new method for getting the begin or end time for the provider itself.  

There are currently usages (and supporting implementations) of `get_forcing_output_time_begin` and `get_forcing_output_time_end` that attempt to obtain this for the instance itself, even though these functions are intended to be used strictly with a particular provided forcing (see [discussion here](https://github.com/NOAA-OWP/ngen/pull/335#discussion_r748467007)).   Those need to be corrected once the more appropriate functions for the provider itself are available.

**Comment by mattw-nws** [comment]
This is "solved" with the DataProvider interface refactor (#406)... which now has _only_ a method to get the whole dataset's start and end time, and no methods per-variable. Going to close this as it would be hard to make it relevant at this stage. The Forcing/DataProvider mechanism may evolve to where this discussion is moot... but in any case, we still don't have a scenario where different variables have different time ranges... I have a hunch that when we do this may become multiple "layers" of forcing instead of one provider anyway.
