### ISSUE TITLE
Setting ${BOOST_ROOT} doesn't seem to help -- Boost has to be system searchable

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/ngen#362]
Using Ubuntu 20.04, the default Boost library (`sudo apt install libboost-dev-all`) is v1.71. NGEN requires 1.72 (or 1.72+ presumably), so a custom Boost installation is needed. So I pulled the latest library from https://www.boost.org/users/download/

These cmake lines seems to indicate that the script will respect a custom BOOST library installed somewhere: 
https://github.com/NOAA-OWP/ngen/blob/895708ae3052ce35687a16cf8c199873f46af262/CMakeLists.txt#L86-L97

But just below that line, this line performs an explicit search for the specified Boost library version, ignoring the $BOOST_ROOT environment variable: 
https://github.com/NOAA-OWP/ngen/blob/895708ae3052ce35687a16cf8c199873f46af262/CMakeLists.txt#L109

Commenting the explicit test exposes embedded tests for system searchability of the Boost libraries, not (apparently) respecting the $BOOST_ROOT (e.g., there are errors about a $Boost_DIR that come from more deeply embedded calls to `find_package`.)

I tried more explicitly specifying the path, as shown here, but that did not solve the later errors. 
https://stackoverflow.com/questions/49816206/cmake-find-package-specify-path

Ultimately, I just built and installed the custom library at the system level -- it seems like BOOST_ROOT wasn't helping too much.

**Comment by jameshalgren** [comment]
@hellkite500 @robertbartel 
Low impact -- more of a documentation issue than anything.

**Comment by PhilMiller** [comment]
I just tried this in an Ubuntu 20.04 container:

```
# env | grep -i boost
BOOST_ROOT=/srv/repos/boost_1_82_0

# cmake -S . -B 2023-04-07-oldboost -DNGEN_ACTIVATE_PYTHON:BOOL=ON -DBMI_C_LIB_ACTIVE:BOOL=ON -DBMI_FORTRAN_ACTIVE:BOOL=ON
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiler: /usr/bin/gcc-8
-- Compiler: /usr/bin/g++-8
-- Found Boost: /srv/repos/boost_1_82_0 (found suitable version "1.82.0", minimum required is "1.72.0")  
INFO UDUNITS_ACTIVE not defined
Looking for UDUNITS-2...
-- Found UDUNITS2: /usr/lib/aarch64-linux-gnu/libudunits2.so  
INFO Using UDUNITS2 at /usr/lib/aarch64-linux-gnu/libudunits2.so and /usr/include
-- Found Python: /srv/venvs/2023-07-05-test2/bin/python3 (found suitable version "3.8.10", minimum required is "3.6.8") found components: Interpreter Development NumPy 
-- pybind11 v2.10.1 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python: /srv/venvs/2023-07-05-test2/bin/python3 (found version "3.8.10") found components: Interpreter 
-- Configuring done
-- Generating done
-- Build files have been written to: /srv/repos/ngen/2023-04-07-oldboost
```

I'm a little bit perturbed, because I see two different "Found Boost" lines, with different results!

Builds without a system boost installation at all seem to work fine:
```
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiler: /usr/bin/gcc-8
-- Compiler: /usr/bin/g++-8
-- Found Boost: /srv/repos/boost_1_82_0 (found suitable version "1.82.0", minimum required is "1.72.0")  
INFO UDUNITS_ACTIVE not defined
Looking for UDUNITS-2...
-- Found UDUNITS2: /usr/lib/aarch64-linux-gnu/libudunits2.so  
INFO Using UDUNITS2 at /usr/lib/aarch64-linux-gnu/libudunits2.so and /usr/include
-- Found Python: /srv/venvs/2023-07-05-test2/bin/python3 (found suitable version "3.8.10", minimum required is "3.6.8") found components: Interpreter Development NumPy 
-- pybind11 v2.10.1 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found Boost: /srv/repos/boost_1_82_0 (found version "1.82.0")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python: /srv/venvs/2023-07-05-test2/bin/python3 (found version "3.8.10") found components: Interpreter 
-- Configuring done
-- Generating done
-- Build files have been written to: /srv/repos/ngen/2023-04-07-oldboost
```

I'll try to look into why one site would pick up a system installation over the hinted copy.

**Comment by PhilMiller** [comment]
CMake version doesn't make a different (spanning 3.16 through 3.26)

Removing the lower-level calls to `find_package(Boost)` other than in the root `ngen/CMakeLists.txt` seems to resolve things. Configuration only prints one "Found Boost" line, and the build succeeds.

Changing *all* of the other `find_package(Boost)` lines to `find_package(Boost 1.72.0 REQUIRED)` also results in just one print of the "Found Boost" line, and the build succeeding.

Changing just some of the lines results in additional instances of "Found Boost" appearing in the output, with results on each varying depending on whether the version requirement was specified. I fully expect that would result in a quietly and inscrutably broken build, with ABI mismatches and ODR violations.

I'm going to propose removal of all the subsidiary `find_package(Boost)` calls, since they're redundant with the root CMakeLists.txt's call, and actively cause trouble.

**Comment by PhilMiller** [comment]
As far as I can tell from `cmake --debug-find`, the underlying cause of this behavior is that `find_package(Boost)` will prefer an installation with the generated `BoostConfig.cmake` file that appears in the distro packages or a full installation over a Boost source tree in which that's not present, but in which it then finds `boost/config.hpp`. With the version specified, it find the system installation, but rejects it and continues its search, eventually returning the desired copy.

I don't quite know why subsequent calls without the version specified repeat the search process, rather than accepting the already-found instance from the earlier call.
