### ISSUE TITLE
Segfault when using `output_variables` in realization config of a bmi_multi formulation

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen#410]
when output_variables and/or output_header_fields are present in the realization_config, the dynamic pointer cast in `Bmi_Multi_Formulation::get_var_value_as_double)` fails.  The results in `nested_module`  being `nullptr` and leads to a segfault.

Here is the failing [pointer cast](https://github.com/NOAA-OWP/ngen/blob/d53d110829da6e91512009fa63b23f310fb62632/include/realizations/catchment/Bmi_Multi_Formulation.hpp#L559)

## Current behavior
Seg fault occurs when trying to use output_variables in Bmi_Multi_formualtion

## Expected behavior

The formulation should run and the requested variables should be output

## Steps to replicate behavior (include URLs)

1.  Add an `output_variables` key  to a `bmi_multi` formulation definition in the realization config.

**Comment by lcunha0118** [comment]
(Not sure if this issue is related)  my understanding is that you should be able to output any variable that is set as a bmi output for any of the models. The current version seems to only allows to configure output variables that are either bmi input or output for the LAST model. 

Example: I am running Noah-owp and CFE. SNEQV is an bmi output for Noah-owp but  IS NOT input to CFE. When I try to output it, I get the following error: 

terminate called after throwing an instance of 'std::runtime_error'
  what():  BMI C model failed to get variable type for SNEQV.
Aborted (core dumped)
