### ISSUE TITLE
`assert` should not be passed a string literal

### ISSUE THREAD

**Issue by PhilMiller** [NOAA-OWP/ngen#557]
[include/utilities/python/InterpreterUtil.hpp](https://github.com/NOAA-OWP/ngen/blob/master/include/utilities/python/InterpreterUtil.hpp#L295)

> `assert("Unexpected value of venv_dir in InterpreterUtil::getDiscoveredVenvPath()!");`

This is probably meant to call `abort`, since the `bool`-conversion of a string literal is always `true`

**Comment by mattw-nws** [comment]
Guilty, I suppose. After #546 though, the last 2/3 of this function will probably just be removed, right? I think made this `assert` instead of `throw` as it could only be the result of an erroneous result thrown from `searchForVenvDir`, but that will probably be removed? (But yes, that's technically not what you're supposed to pass to `assert()`.
